### ISSUE TITLE
Exception when trying to /on /off the printer

### ISSUE THREAD

**Issue by fabiuzzo77** [jacopotediosi/OctoPrint-Telegram#383]
Hi, 

when trying to swtich on/off the printer it does't work, I see in the logs:

```
2021-10-25 20:58:47,201 - octoprint.plugins.telegram.listener - INFO - Got a command: 'SwitchOff' with parameter: '' in chat 305823880
2021-10-25 20:58:47,202 - octoprint.plugins.telegram.listener - ERROR - Exception caught! 'SwitchOff'
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_telegram/__init__.py", line 97, in loop
    self.processMessage(message)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_telegram/__init__.py", line 176, in processMessage
    self.handleCallbackQuery(message)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_telegram/__init__.py", line 186, in handleCallbackQuery
    self.handleTextMessage(message["callback_query"], chat_id, from_id)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_telegram/__init__.py", line 631, in handleTextMessage
    if self.main.isCommandAllowed(chat_id, from_id, command):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_telegram/__init__.py", line 2532, in isCommandAllowed
    if self.chats[chat_id]["commands"][command]:
KeyError: 'SwitchOff'
```

I have PSU Control plugin, I use a wifi plug with a webhook to control the power supply.

Can you help?

I'm running on Python3 with octo 0.17 and version 1.6.5 of Telegram Notification

Thanks!

**Comment by fabiuzzo77** [comment]
What did you mean exacly? With pi user I've created a bash script that calls a webhook to switch PSU, so execution rights are granted to pi

**Comment by giloser** [comment]
![image](https://user-images.githubusercontent.com/12090417/140651300-27c34fd9-9395-4869-93ab-e53d0010b9d4.png)
